version: '3.9'

services:
  postgres:
    container_name: trading-database
    image: library/postgres:13
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    restart: always
    networks:
      - trading-net

networks:
  trading-net:
